### PR TITLE
Conformance Test Results for MetaHub

### PR DESCRIPTION
**Pull request by ChristianKniep**

### CODE REVIEW

**Comment by ChristianKniep** [comment]
> DCO needs to be set on the commit (see the description on DCO error for how to fix it), and I think we want the commit message updated, too.

`-s` done with the last commit.
 
> Does MetaHub not have support for any push or query operations (like listing tags), or is that support not OCI compliant?

listing tags should be included, but it's also skipped by others ([bundle-bar](https://deploy-preview-94--oci-conformance.netlify.app/static/v1.0/reports/bundle-bar/), [azure](https://deploy-preview-94--oci-conformance.netlify.app/static/v1.0/reports/azurecontainerregistry/)).

> And a quick FYI that the site is hard to read when my desktop is in dark mode:

Yeah, I am getting my hands dirty with JavaScript - I'll get to that eventually...

**Comment by sudo-bmitch** [comment]
> > DCO needs to be set on the commit (see the description on DCO error for how to fix it), and I think we want the commit message updated, too.
> 
> `-s` done with the last commit.

For https://github.com/opencontainers/oci-conformance/pull/94/commits/ec3e78d8293172538fcba0b9a734a86b07b6c3a4 can you also adjust the commit messages? Should be a `git rebase -i ec3e78d8293172538fcba0b9a734a86b07b6c3a4^`, and then change `pick` to `reword` on the specific commit. You'll need to force push that change. 

> > Does MetaHub not have support for any push or query operations (like listing tags), or is that support not OCI compliant?
> 
> listing tags should be included, but it's also skipped by others ([bundle-bar](https://deploy-preview-94--oci-conformance.netlify.app/static/v1.0/reports/bundle-bar/), [azure](https://deploy-preview-94--oci-conformance.netlify.app/static/v1.0/reports/azurecontainerregistry/)).

Bundle bar and Azure each ran the push, discovery, and management tests, which is why it stood out that MetaHub didn't.

**Comment by ChristianKniep** [comment]
I added the DISCOVERY tests while I was at it. Anything else I missed?

**Review by sudo-bmitch — APPROVED** [review]
Thanks for the updates. The only other change I'd want is to squash the commits, but this looks good enough to merge if another approved seconds it.

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Are we allowing squash and merge?

**Comment by sudo-bmitch** [comment]
> Are we allowing squash and merge?

We'll find out if @jdolitsky yells at me. 😁

**Pull request merged**
