### PR TITLE
MAINTAINERS: defer to Ram

### PR DESCRIPTION
**Pull request by hallyn**
Ram is on my team, and is the one actively working on this and related projects.

Signed-off-by: Serge Hallyn <serge@hallyn.com>

### CODE REVIEW

**Review by jdolitsky — APPROVED** [review]
sounds good to me

**Review by tianon — APPROVED** [review]
:+1:

**Comment by vsoch** [comment]
How does one validate a person? :thinking:

**Review by SteveLasker — APPROVED** [review]
LGTM

**Comment by rchincha** [comment]
> LGTM. We need 2/3rds on this and we should also get a 👍 from @rchincha to make sure he wants to be volunteered as a mod.

Acknowledged and agreed. Thanks.

**Pull request merged**
