### PR TITLE
Zot-url-update

### PR DESCRIPTION
**Pull request by maxknee**

### CODE REVIEW

**Review by jdolitsky — APPROVED** [review]

**Comment by vsoch** [comment]
Should we be worried about the CI failures?

**Comment by jdolitsky** [comment]
yea :/ we should:
```
12:34:41 PM: $ (cd products-page-generator/ && GIT_COMMIT=$(git rev-parse HEAD) go run main.go && cd jekyll/ && bundle config set --local path 'vendor/bundle' && bundle install && bundle exec jekyll build && cp favicon.ico _site/)
12:34:41 PM: bash: line 0: cd: products-page-generator/: No such file or directory
```

its like it doesnt have access to the source code / it doesnt clone it down. maybe a netlify API change

**Comment by vsoch** [comment]
What is `products-page-generator`?

**Comment by jdolitsky** [comment]
@vsoch it's a tiny app that generates markdown based on all submitted results: https://github.com/opencontainers/oci-conformance/tree/main/products-page-generator

**Comment by vsoch** [comment]
Can we try a re-run? I just did a debug run and everything looks okay: https://app.netlify.com/sites/oci-conformance/deploys/62f6c4deebc5ce0008f8e040. If the bug is still there, it must be something about the branch, and if that's the case @maxknee update your netlify.toml to have a command that shows what's there (but not yet, only after we try a re-run)

```yaml
[build]
    command = "(echo $PWD && ls && cd products-page-generator/ && GIT_COMMIT=$(git rev-parse HEAD) go run main.go && cd jekyll/ && bundle config set --local path 'vendor/bundle' && bundle install && bundle exec jekyll build && cp favicon.ico _site/)"
    publish = "products-page-generator/jekyll/_site/"
```

**Review by vsoch — APPROVED** [review]
Huzzah! https://62f81d458175d50008ae2461--oci-conformance.netlify.app/

**Pull request merged**
