### PR TITLE
Conformance results for olareg

### PR DESCRIPTION
**Pull request by sudo-bmitch**
This adds the conformance results for olareg. Details about the project can be found at https://github.com/olareg/olareg. 

This is the first entry in the v1.1 directory, so we should be sure that doesn't break any rendering. The one thing missing from the project is a logo, hopefully that doesn't mess anything up.

### CODE REVIEW

**Comment by sudo-bmitch** [comment]
Holding this as a draft while looking into why the supported workflows don't have the expected checkboxes.

**Review by jdolitsky — APPROVED** [review]
report looks nice, project looks nice. overall looks nice

**Review by rchincha — APPROVED** [review]
lgtm

**Review by tianon — APPROVED** [review]
Agreed, interesting project, report looks fine -- it does make me wonder about "weekend hack projects" in this list, but we've got some existing precedent for that and I guess the number of folks _actually_ writing registries is already a small set and functionally the ratio of those running through the conformance tests and submitting them is even lower so maybe it's fine. :+1:

**Pull request merged**
