### PR TITLE
Add draft workflow for keppel

### PR DESCRIPTION
**Pull request by pmengelbert**

### CODE REVIEW

**Comment by pmengelbert** [comment]
@majewsky We can't quite get this running, as we're not sure how to handle the authorization end of it. Would you care to take a look and let us know how we can get this up and running? Thanks!

**Comment by pmengelbert** [comment]
ping @majewsky -- can we get some information on this?

**Comment by jdolitsky** [comment]
Going to close this PR. Please resubmit based on https://github.com/opencontainers/oci-conformance/pull/78

**Comment by majewsky** [comment]
Oh sorry, I never saw this. I will make a note to pick this up in our team when we get the chance.

**Pull request closed without merging**
