### PR TITLE
Add initial maintainers

### PR DESCRIPTION
**Pull request by jdolitsky**
Each maintainer, please

- Verify email used, or suggest change
- Add an approval to this PR

@hallyn @jdolitsky @stevelasker @sudo-bmitch @tianon @vbatts @vsoch

### CODE REVIEW

**Comment by vsoch** [comment]
Seems okay to me! Will we be added as actual maintainers on the repo so we can review, etc.?

**Comment by jdolitsky** [comment]
@vsoch - yes. We still gotta figure out the model for access controls in OCI, but I'm thinking we can create a GitHub maintainer team

**Review by sudo-bmitch — APPROVED** [review]

**Review by tianon — APPROVED** [review]

**Review by SteveLasker — APPROVED** [review]
LGTM

**Review by vbatts — APPROVED** [review]
:cupcake:

**Comment by hallyn** [comment]
LGTM

**Comment by jdolitsky** [comment]
thanks everyone! in the process now of getting a github team setup. check for invites

**Pull request merged**
