### PR TITLE
Update docker/distribution workflow

### PR DESCRIPTION
**Pull request by pmengelbert**
Build docker image from source instead of pulling pre-built image.

@caniszczyk

### CODE REVIEW

**Comment by pmengelbert** [comment]
@dmcgowan

**Comment by dmcgowan** [comment]
LGTM

These can only run after merge?

**Comment by pmengelbert** [comment]
@dmcgowan Yes, they will run after merge. I'll set up a branch with a demonstration, but please note the branch won't have access to the s3 bucket where the report lives. So the github action will "fail", but if you look at the test results they work correctly.

**Comment by pmengelbert** [comment]
@dmcgowan Distribution registry passing the pull workflow:
https://github.com/bloodorangeio/oci-conformance/runs/731124216?check_suite_focus=true

**Comment by pmengelbert** [comment]
@caniszczyk This should be good to merge -- anything else you need from us?

**Pull request merged**
